### ISSUE TITLE
Column Arrangement in Available Assets in Data Not Working

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1149] opened 2017-12-07 13:22 UTC
Tipically, when user is widening or narrowing the columns in certain tab, all the other columns get narrowed and/or widened, so all the columns take up the entire length of a window.
But in this case, if user narrows columns in Data -> Available Devices/Available Assets/Available Channel Metrics, others do not adopt to new situation, so now we can get window with empty right side (look at the screenshot).

Testflow: 
1. Login as kapua-sys
2. Go to Data -> By Asset -> Available Devices/Available Assets/Available Channel Metrics
3. Try to narrow columns, as showed in screenshot.
**This should not be possible, but nevertheless, Kapua allows user to narrow columns in this unusual way.**

![screen shot 2017-12-07 at 13 21 03](https://user-images.githubusercontent.com/15121999/33717353-dff643ae-db59-11e7-9e5a-2cacbc16b5bf.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by LeoNerdoG** [comment] 2018-01-16 08:03
Hi @lorthirk ,
issue still persists in Available Channel Metrics, if only **Metric** or only **Type** column selected. If both metrics are selected, the issue is somehow resolved. 
In **Available Devices** part and **Available Assets** everything is OK: 

Screenshot No. 1 (If only **Metric** column selected):
<img width="1438" alt="screen shot 2018-01-16 at 08 55 06" src="https://user-images.githubusercontent.com/15121999/34977740-00234dc8-fa9c-11e7-9030-ae6239b9620e.png">

Screenshot No. 2 (if only **Type** column selected):
<img width="1438" alt="screen shot 2018-01-16 at 08 55 18" src="https://user-images.githubusercontent.com/15121999/34977747-05850130-fa9c-11e7-92b9-8c5ef8c3e04c.png">

**Comment by lorthirk** [comment] 2018-01-16 11:40
Duplicate of #1147

**Closed by lorthirk** 2018-01-16 11:40 UTC
Labels: console-gwt, enhancement
