### ISSUE TITLE
Lockout policy conflicts with Swagger UI

### ISSUE THREAD

**Issue by Sealdolphin** [eclipse/kapua#1507] opened 2018-03-14 13:30 UTC
Hi,

It is a very annoying and rare problem I have experienced, but I could not repeat until now. When I am using the Swagger UI and the Kapua WebConsole simultaneously, after switching from one to another I lose my authentication credentials, so I have to log in again. The problem is, that if I change the System Admin (kapua-sys) password, he could get locked out. It does not depend on whether the Lockout Service is enabled or not, or if it is how it is configured. The system admin gets locked out with the preset Lockout Service settings.

Note: The lockout happens instantly, you don't even have to type a wrong password...

Here is the test sequence:

1. Install Kapua and log in with _kapua-sys_
2. Create a child account ("c_account")
3. Enable infinite child users
4. **Disable Lockout service**
5. Create a new user of c_account (c_user, pass: new_password)
6. Grant him ALL permissions
7. **Change system admin password** (clicking change password in the top right corner)
[new pass: new_password]
8. Go to Swagger UI
9. Request authentication/user and log in with c_user/new_password (not with sys-admin)
10. Go back to web console (you will be dropped out after a few seconds)
11. Try to log in with kapua-sys/new_password
12. It will say that the account is locked contact System Administrator...

NOTE: I also observed some things which can be helpful
- As in my example the child account's user password and the system admin changed password was the same. (but I don't think that matters)
- The system admin has been locked out, however I still could use the child account's user
- The system admin was useless both in the web console and the Swagger UI
- The system admin lockout was resolved after a day passed from last login attempt (but I think that was just the default 10800 seconds of the Lockout Service)
- It **only** occured **when I changed the** system admin **password**
- Because of the long resolution time I couldn't run more experiment on this matter
- I cannot change the Kapua settings until I create a child account (the settings are grey)
![image](https://user-images.githubusercontent.com/26169252/37404990-ba40bf5a-2793-11e8-91cd-e92f455527eb.png)
- After I have a child account I switch to that account, go to settings, change back to kapua-sys, refresh, and THEN I can change the settings.

It was extremely frustrating the first time and now that I can recreate it and have fears using the web console and the Swagger UI simultaneously because of that. Thank you for your help.

**Comment by lorthirk** [comment] 2018-03-14 14:52
Hi @Sealdolphin,

Thanks for the report. I'm going to investigate on this.

However, about the last two points: it's actually by design that a user cannot change its own Settings, but rather a user from the parent account should be the one entitled to change them via the Child Accounts --> Settings view. This means that you cannot change settings for the root account, but since it's meant to be only a "container" for children accounts you shouldn't need to change them anyway. All the settings should stay disabled since that page is meant as a review only, so it's actually an issue if you manage to somehow "unlock" them. I'll investigate on this as well.

**Comment by lorthirk** [comment] 2018-03-14 15:19
Let me give you a first update on some of the items:

- There's actually a bug in Password Change when a child account is selected in the top right menu. I'll file an issue for that.
- It's right that you get locked out from kapua-sys if you enter the password wrong, because you're disabling the Lockout Policy on the child account, not on kapua-sys.
- I'm not able to reproduce your last remark, the one about being able to enable fields in Settings when switching to a Child Account and back. Can you please retry, and maybe add some more detail?
- We're still investigating the conflict between the Swagger session and the Kapua session

**Comment by Sealdolphin** [comment] 2018-03-14 16:58
That was what I expected, so when I changed the Kapua settings it was the child account's settings and the sysadmin settings cannot be changed, right?

**Comment by lorthirk** [comment] 2018-03-15 08:39
Yes, if you're talking about the Settings tab in the Child Accounts view. The Settings view from the main menu, instead, should always be read only, useful to check the current settings.

**Comment by lorthirk** [comment] 2018-03-16 16:16
Update: the Session conflict is now tracked by #1520

**Comment by Coduz** [comment] 2018-06-28 09:55
Closing this since tracking is in another issue.

**Closed by Coduz** 2018-06-28 09:55 UTC
Labels: bug
