### ISSUE TITLE
Multiple Same Endpoints Can Be Implicitly Created

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2248] opened 2018-12-11 08:01 UTC
There is a way to create multiple same endpoints. If you first login with kapua-sys and create "kapua.com/kapua.com/123/false" endpoint and then create a child account and within that account same endpoint (see the detailed testflow bellow), kapua does not report any errors, although this same endpoint already exists. If user now switches to kapua-sys (top parnet account), there are two identical endpoints if the original one (from kapua-sys) is deleted.

This can be done for all child accounts, so for example, if you have 20 child accoutns, and every account has "kapua.com/kapua.com/123/false" endpoint, then you see 20 identical endpoints in kapua-sys account.

**Testflow:**
1. Login as kapua-sys 
2. Go to Endpoints, create a sample endpoint (e.g. kapua.com/kapua.com/123/false)
3. Go to Child Accounts, create a child account (e.g. child0)
4. Switch to child account, go to Endpoints, create endpoint "google.com/google.com/123/false"
5. Now add another endpoint "kapua.com/kapua.com/123/false" and delete the "google.com" endpoint
6. Repeat steps 3-5 two more times (create child1 and child2) 
7. Go back to kapua-sys and delete the only endpoint. 
**Observe how all the endpoints from all the child accounts are gathered - they are all the same.**

**Expected behavior**
I guess this should not be allowed - Kapua should be cross-checking if the endpoints with these parameters already exists?

**Screenshot No. 1 (situation in every account before endpoint in kapua-sys is deleted):**
![screenshot 2018-12-11 at 08 41 08](https://user-images.githubusercontent.com/15121999/49786179-33d3c780-fd23-11e8-80b4-41a7d86dce51.png)

**Screenshot No. 2 (situation after the endpoint in kapua-sys is deleted):**
![screenshot 2018-12-11 at 08 41 15](https://user-images.githubusercontent.com/15121999/49786176-31716d80-fd23-11e8-96af-951918f62dc2.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by ct-anaalbic** [comment] 2019-05-09 10:29
Hi @Coduz 

Is this really issue? If user creates endpoint first in kapua-sys account and than in some other child account with same name like in kapua-sys account, this action is allowed. Is this ok or this action should not be allowed?

Thank you.

Regards,
Ana

**Comment by Coduz** [comment] 2019-05-10 09:37
Hi all, 

I think that the real problem here is that in `kapua-sys` can see all of the endpoints. That view is supposed to show only the ones of `kapua-sys`.

Is the view showing all available endpoints instead, then? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment] 2019-05-10 10:24
Hej @coduz,
no, kapua-sys cannot see all the endpoints. There is no "real" issue here (because of the nature of Endpoints) but user can have feeling that certain enpoindts are not deleted (because there are multiple same ednpoints in different accounts - see text in original issue). 

So the basic queestion here is: Is it OK fur user to create same (identical) endpoints as its parents have or not?

**Comment by Coduz** [comment] 2019-05-13 14:12
That is ok.

The problem I see is that the situation in screenshot n2 shouldn't never happen!

**Comment by LeoNerdoG** [comment] 2019-05-14 05:21
Hey @Coduz,
I have updated the upper comment and tried again today and issue still persists. i know that the situtaion from second screenshot should never happen, that is why I have opened this issue 😄 .

**Comment by Coduz** [comment] 2019-05-14 08:58
I've just verified the thing.

The problem is that if an account has no endpoints and there is also no endpoint set in the parents accounts (even `kapua-sys`) the account see all available endpoints registered.

It is unlikely to happen (since we manually add the defaults endpoints for each env) but I'll put a fix on this.

Regards, 

_Alberto_

**Comment by Coduz** [comment] 2020-05-04 14:55
Closing this issue as per last comment!

**Closed by Coduz** 2020-05-04 14:55 UTC
Labels: Bug
