### ISSUE TITLE
Asset Tab In Devices Disabled

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2007] opened 2018-09-13 12:08 UTC
Although device is online (connected) and has available assetes, the Assets tab in Devices is disabled. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to kapua that has some assets (e.g. device0)
3. Go to Devices, select device0 and observe the tabs panel.
**Assets tab is disabled, but it should be enabled.**

**Expected behavior**
Assets tab should be enabled. 

**Screenshot:**
![screen shot 2018-09-13 at 13 49 19](https://user-images.githubusercontent.com/15121999/45486621-1317c800-b75c-11e8-8d45-ce9ea8933f63.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment] 2018-09-13 14:54
Asset Tab is disabled if the device does not have "ASSET-V1" app

**Comment by LeoNerdoG** [comment] 2019-05-06 10:39
@coduz should we close this as Wontfix or do you have any other suggestions?

**Comment by Coduz** [comment] 2019-05-07 09:01
The activation of the tabs depends on the Device application available. 
If there is no application on the device, the related tab is disabled.
So is by design what you noticed.

We close this as `wontfix`

**Closed by Coduz** 2019-05-07 09:01 UTC
Labels: bug, console-gwt
