### ISSUE TITLE
Device Configuration Refreshed Twice

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1344] opened 2018-02-01 07:51 UTC
When User updates configuration on a live device, the list/window is refreshed twice (first time and then immediatelly again). 

Testflow: 
1. Login as kapua-sys
2. Connect a live Kura device to Kapua (e.g. device1)
3. Go to Devices -> device1 -> Configuration and change any of the services parameters
**At this point Kapua will refresh the window twice.**

Browsers used:
- Google Chrome (Version 64.0.3282.119 (Official Build) (64-bit)))
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.1  (64-bit))
- Opera (Version 50.0.2762.67)

**Comment by lorthirk** [comment] 2018-02-01 11:04
This should be already covered by #1098 and fixed in branch `fix-devices_view_usability_improvements`. Can you confirm?

**Comment by LeoNerdoG** [comment] 2018-02-01 11:24
@lorthirk yes, that is correct, this issue is resolved in branch `fix-devices_view_usability_improvements`.

**Comment by lorthirk** [comment] 2018-02-08 10:46
Duplicate of #1098

**Closed by lorthirk** 2018-02-08 10:46 UTC
