### ISSUE TITLE
about streams

### ISSUE THREAD

**Issue by zhouyue123** [eclipse/kapua#783] opened 2017-08-25 08:37 UTC
when i input the parameter

![1](https://user-images.githubusercontent.com/28722594/29706182-6ac17e70-89b3-11e7-88a4-cd961b963c88.png)

 and Parameter content type is application/json ,server response 500,error message:
Descriptor: XMLDescriptor(org.eclipse.kapua.message.KapuaChannel --> [DatabaseTable(channel)])
        at org.eclipse.persistence.exceptions.DescriptorException.missingClassIndicatorField(DescriptorException.java:959)
        at org.eclipse.persistence.internal.oxm.XMLRelationshipMappingNodeValue.processChild(XMLRelationshipMappingNodeValue.java:83)

 , this is parameter type wrong?

**Comment by lorthirk** [comment] 2017-08-25 09:31
Duplicate of #782

**Closed by lorthirk** 2017-08-25 09:31 UTC
