### ISSUE TITLE
Long Account Name Not Displayed Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1192] opened 2017-12-13 09:48 UTC
If end-user creates kapua account with very long name (256 characters), its name is not properly displayed when loged in as user under this account (look at the screenshot). 

Testflow: 
1. Login as kapua-sys
2. Go to Child Accounts, create a child account with very long name (256 characters - look at the screenshot)
3. Add user to newely created child account (e.g. kapua-user1)
4. Logout as kapua-sys and login as user just created (kapua-user1)
**Look at the screenshot: If account name is too long, it is not displayed properly.**

<img width="1436" alt="screen shot 2017-12-13 at 10 16 34" src="https://user-images.githubusercontent.com/15121999/33932298-dc4c8fae-dff2-11e7-93c2-98302d3a1299.png">

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment] 2018-01-22 13:42
Duplicate of #1191

**Closed** 2018-01-22 13:42 UTC

**Comment by lorthirk** [comment] 2018-03-19 11:33
Unfortunately I had to revert #1382 with #1521 because with that implementation the account name would be partially hidden most of the time if it's more than a few characters long, which is a very common scenario, for sure more than the one described in this issue.

**Comment by LeoNerdoG** [comment] 2018-03-19 14:59
I am reopening as PR #1382 has been reverted.

**Comment by LeoNerdoG** [comment] 2018-03-19 14:59
This should be reopened as PR #1382 has been reverted.
