### ISSUE TITLE
How to connect device to Kapua for particular user with their credentials ?

### ISSUE THREAD

**Issue by VivekPowar** [eclipse/kapua#764] opened 2017-08-01 06:12 UTC
@ctron  @lorthirk Actually device is connected to kapua with one user credentials but that device also shows for other user where that user's credentials are different. So is there any way to connect device for particular user with their credentials is their any Roles and Permissions needed

**Comment by Coduz** [comment] 2017-08-01 08:47
Hi @VivekPowar , 

I don't think I understood the request.

You want another user to connect the device?

**Comment by VivekPowar** [comment] 2017-08-01 09:23
Hi @Coduz 
i created 2 user with different username and password in kapua and i am connecting device with 1 credentials details 
![image 3](https://user-images.githubusercontent.com/25997057/28818429-c06b55ec-76c8-11e7-910b-c01f12c241a0.jpg)

            final Client client = KuraMqttProfile.newProfile(FuseClient.Builder::new)
                    .accountName("vivek")
                    .clientId("mobile_vivek")
                    .brokerUrl("tcp://192.168.1.200:1883")
                    .credentials(userAndPassword("vivek", "Vivek@Powar12345"))
                    .build();

![image 4](https://user-images.githubusercontent.com/25997057/28818613-356232a8-76c9-11e7-85f6-05c217d8b0c5.jpg)

so this user only can see the connected device but now in my case both user is showing that device, i want to see that device in that user list only

**Comment by Coduz** [comment] 2017-08-01 09:34
That is by design. 
That is the list of devices registered (connected and not connected) to the platform. 
A user that has `device:view` permission can see all devices.

**Comment by VivekPowar** [comment] 2017-08-01 09:36
@Coduz  so is there any changes to do with permission of user so that i will see only that user's device

**Comment by Coduz** [comment] 2017-08-01 09:45
You can assign a group to a device, and give the user a permission of `device:view:{groupId}`.
Then the user will be able to see only devices on the specific group. 
But other user with `device:view` will be able to see the whole set of devices

**Comment by VivekPowar** [comment] 2017-08-01 10:40
@Coduz i created one group and assigned to that device and then is there any user permission needed ?

**Comment by VivekPowar** [comment] 2017-08-02 11:07
@Coduz i got solution thanks

**Comment by VivekPowar** [comment] 2017-08-04 07:45
@Coduz can we get user wise Topic  ?

**Comment by Coduz** [comment] 2017-08-04 10:07
Follow #768 :) I'll close this

**Closed** 2017-08-04 10:07 UTC
Labels: question
