### ISSUE TITLE
If a query returns zero elements, then total count is always null

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#510] opened 2017-04-25 08:54 UTC
Starting a query with `setAskTotalCount(true);`, but returning zero entries will return a result with a `getTotalCount() = null`.

I would expect `getTotalCount()`to never return `null` if `setAskTotalCount(true)` was called.

**Comment by lorthirk** [comment] 2019-07-12 15:05
I'm closing this since I couldn't reproduce it, given that `ResultList.totalCount` is a `long`. Of course it will be reopened should we get a positive test case.

**Closed by lorthirk** 2019-07-12 15:05 UTC
Labels: bug
