### ISSUE TITLE
Unable to login to console using the default username/password

### ISSUE THREAD

**Issue by dknezevic** [eclipse/kapua#384] opened 2017-03-16 15:06 UTC
Hi guys,
I've successfully cloned and built the Kapua project (in development environment), started the database service, the broker and the Tomcat server.
The problem is that, when trying to login to the console using default credentials, i get an internal error.
This occurs only when i provide the correct username and password, when the wrong credentials are entered i get the expected access denied message.

The only details i can provide is the message i get in the small popup window which reads:

_Login Failed.
An internal error occurred: An internal error occurred: Error during Persistence operation.._

Is this a known issue? 
Am i doing something wrong?
Is there a workaround?
Is there something else that i could provide in order to make it easier for you to solve it?

![screenshot from 2017-03-16 15-58-14](https://cloud.githubusercontent.com/assets/10669852/24002932/4d989d90-0a62-11e7-954b-b2ab6fdd86dd.png)

Regards,
Dusan Knezevic

**Comment by lorthirk** [comment] 2017-03-16 15:08
Hello Dusan,

For sure a Tomcat log would help! Could you provide that one?

--
Claudio Mezzasalma | Eurotech

Da: dknezevic <notifications@github.com>
Risposta: eclipse/kapua <reply@reply.github.com>
Data: giovedì 16 marzo 2017 16:06
A: eclipse/kapua <kapua@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [eclipse/kapua] Unable to login to console using the default username/password (#384)


Hi guys,
I've successfully cloned and built the Kapua project (in development environment), started the database service, the broker and the Tomcat server.
The problem is that, when trying to login to the console using default credentials, i get an internal error.
This occurs only when i provide the correct username and password, when the wrong credentials are entered i get the expected access denied message.

The only details i can provide is the message i get in the small popup window which reads:

Login Failed.
An internal error occurred: An internal error occurred: Error during Persistence operation..

Is this a known issue?
Am i doing something wrong?
Is there a workaround?
Is there something else that i could provide in order to make it easier for you to solve it?

[creenshot from 2017-03-16 15-58-14]<https://cloud.githubusercontent.com/assets/10669852/24002932/4d989d90-0a62-11e7-954b-b2ab6fdd86dd.png>

Regards,
Dusan Knezevic

**Comment by lorthirk** [comment] 2017-03-16 16:22
Hello @dknezevic,

For sure a Tomcat log would help! Could you provide that one?

**Comment by dknezevic** [comment] 2017-03-16 17:01
Hi Claudio,
thanks for the prompt reply.
I have attached the catalina.out file, i suppose that this is the right one.
If not, please let me know.

[catalina.txt](https://github.com/eclipse/kapua/files/848461/catalina.txt)

**Comment by lorthirk** [comment] 2017-03-16 17:25
It seems you're missing ATHT_ACCESS_TOKEN table from the DB. Could you please check if it's actually on the DB? You can point your browser at `http://192.168.33.10:8082` and configure the connection as H2 server, jdbc://192.168.33.10:3306/kapuadb as the URL, and kapua for both username and password. Also, are building from the `develop` branch?

**Comment by lorthirk** [comment] 2017-03-17 08:18
And another couple of question: it seems from the URL that you're using the Vagrant setup. Is that the develop or the demo machine? When did you rebuild both the base box and the one you're using the last time?

**Comment by dknezevic** [comment] 2017-03-17 08:55
You are correct, i am missing the ATHT_ACCESS_TOKEN table in the DB.
![image](https://cloud.githubusercontent.com/assets/10669852/24035688/e0646f52-0af6-11e7-80c2-44672b1209e6.png)

I have cloned the repo and followed the instructions in the readme file (so i suppose that i am using the default (develop) branch. 
I am using the develop machine. I have built both base-box and the develop yesterday.

I will now try to do everything again from the start. If you have any other suggestions (e.g. do not use vagrant machine, pull the master branch etc) i am ready to try them out.

**Comment by ctron** [comment] 2017-03-17 08:58
Just out of curiosity, could you give the docker approach a try if that works for you?

https://github.com/eclipse/kapua/blob/develop/assembly/README.md

**Comment by dknezevic** [comment] 2017-03-17 08:59
Hi ctron,
Sure, I will do it right away...

**Comment by lorthirk** [comment] 2017-03-17 09:57
@dknezevic, I see you're missing more than that table -- indeed you should have 18 tables in total, not just 10. Clearly something went wrong when creating the database migration.

Out of curiosity, do you remember whether you started before the broker or the web server?

**Comment by dknezevic** [comment] 2017-03-17 10:32
@lorthirk, I always started the broker first, as this is the order described in the readme

**Comment by dknezevic** [comment] 2017-03-17 10:54
@ctron,
i have successfully build and run kapua using docker. I have managed to log in into the console using the provided credentials.

Is this the preferred way to run docker?

**Comment by ctron** [comment] 2017-03-17 12:26
@dknezevic This is a supported way, what ever works best for you.

**Comment by dknezevic** [comment] 2017-03-17 12:37
@ctron,
i am once again trying to build using vagrant develop machine (as it seems the preferred way), but as the quickstart manual is not very clear, i think that i will fail again and use the docker approach in the future.

Just for the record how can other services be reached?

Console: http://localhost:8080/console
API: ?
Broker: ?
DB: ?

**Comment by ctron** [comment] 2017-03-17 13:26
API: http://localhost:8081/api
Broker: tcp://localhost:1883 ws://localhost:61614
DB: SQL:3306 http://localhost:8181

Actually you should see all the port mappings in the README.md, of course you can also re-assign them with docker.

**Comment by dknezevic** [comment] 2017-03-17 13:32
@lorthirk 
So just to summarize my experience with the [quickstart manual:](https://github.com/eclipse/kapua/blob/develop/dev-tools/src/main/vagrant/README.md#running-the-kapua-dev-box)

_as a first step, i have cloned the repo using the git clone https://github.com/eclipse/kapua command._

1. Demo machine quick start
$ cd $KAPUA_GITHUB_HOME_DIR/dev-tools/src/main/bin
$ ./start-demo.sh

_This never ends well, if you need it, i can run it again and include the errors_

2. Creating the Kapua base-box
$ cd $KAPUA_GITHUB_HOME_DIR/dev-tools/src/main/vagrant
$ ./start.sh base-box

_I always get the error that the baseBox/create-base-box.sh can not be found (but the file actually exists). After that, i run baseBox/create-base-box.sh script directly and the base-box gets created with no problem._

3. Creating the Kapua dev-box

$ cd $KAPUA_GITHUB_HOME_DIR
$ cd dev-tools/src/main/vagrant
$ ./start.sh develop

_Everything works ok and the develop-box is created. i can do vagrant ssh and connect to the box._

$ mvn clean install -Psql -DskipTests

_When running this **outside** of vagrant (as stated in the doc) i never succeed in building the console module ([kapua-build-dump.txt](https://github.com/eclipse/kapua/files/850651/kapua-build-dump.txt))_

_On the other hand, i can build successfully **inside** the vagrant develop box (after installing maven, which is missing due to the fact that the project is not intended to be build inside the box), but when built that way i got these missing tables._

I will now try to build it inside the vagrant dev-box once more to see if i will get the same results as yesterday and let you know if there are some changes.

**Comment by ctron** [comment] 2017-03-17 13:36
I added the other quickstarts (docker and OpenShift) as well

**Comment by dknezevic** [comment] 2017-03-17 14:21
@ctron the OpenShift link is not working (404).

**Comment by ctron** [comment] 2017-03-17 14:24
@dknezevic Thanks for reporting this. It's fixed now!

**Comment by lorthirk** [comment] 2017-03-20 13:00
@dknezevic thanks for the in depth report. I'll have a look at the script and fix it.

**Closed** 2017-03-21 16:48 UTC
