### ISSUE TITLE
ava.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

### ISSUE THREAD

**Issue by amitghodke90** [eclipse/kapua#738] opened 2017-07-11 13:38 UTC
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
                                                                               at org.eclipse.kapua.gateway.client.Payload$Builder.<init>(Payload.java:34)
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:77)
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:39)
                                                                               at android.app.Activity.performCreate(Activity.java:6679)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.example.amit.mqttdemo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.amit.mqttdemo-2/lib/x86, /system/lib, /vendor/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                               at org.eclipse.kapua.gateway.client.Payload$Builder.<init>(Payload.java:34) 
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:77) 
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:39) 
                                                                               at android.app.Activity.performCreate(Activity.java:6679) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ctron** [comment] 2017-07-11 14:13
Works using proper Java 8 support with Android.

**Comment by ctron** [comment] 2017-07-11 14:14
Duplicate of: https://github.com/eclipse/kapua/issues/732

**Closed by ctron** 2017-07-11 14:13 UTC

**Comment by amitghodke90** [comment] 2017-07-12 05:49
its not working and then why are you closing it?

**Comment by ctron** [comment] 2017-07-12 06:04
It is working if you are using the official java 8 toolchain for Android.

**Comment by amitghodke90** [comment] 2017-07-12 06:12
yes i am using it java 8 for android 
in you case its working because you might not have connected to kapua server thats why you are not getting error you after connecting to kapua its going to send payload message to kapua at that instant error occurs . in you case connecting is not established

**Comment by ctron** [comment] 2017-07-12 06:33
I did connect to Kapua and push telemetry data to Kapua. It did work, I can see the data coming in from the Android application.

**Comment by amitghodke90** [comment] 2017-07-12 06:34
can you send me the url and credentials? also screen shot of data and connected device.

**Comment by ctron** [comment] 2017-07-12 06:46
If that is any help to you, then you should find all the information inside the next screenshots. I also did use `adb reverse tcp:1883 tcp:1883` to map port 1833 from the emulator to my local broker instance running inside docker.

![android_1](https://user-images.githubusercontent.com/202474/28105135-850ab280-66de-11e7-9c49-59b4c18c9e92.png)
![android_2](https://user-images.githubusercontent.com/202474/28105139-882ff326-66de-11e7-9783-38642204d03f.png)

**Comment by amitghodke90** [comment] 2017-07-12 07:44
@ctron 
I do have same code but still getting error not such method join whats gradle dependencies. have added ??

**Comment by ctron** [comment] 2017-07-12 07:53
I will try to prepare an full example on GitHub until the end of the week. No promises though.

**Comment by amitghodke90** [comment] 2017-07-12 07:56
@ctron 
can just send the whatever you done which is currently working example on github till you prepare full example end of week?

**Comment by ctron** [comment] 2017-07-12 08:01
Well I did what I told you already. I will prepare an example which is documented and tested. Otherwise you will only run into more issues.

**Comment by amitghodke90** [comment] 2017-07-12 08:15
@ctron  i will try to solve them.

**Comment by amitghodke90** [comment] 2017-07-12 09:41
@ctron i got expected output and able to send telemetry data to kapua i fixed the issue

**Comment by ctron** [comment] 2017-07-12 13:33
So, what was the cause?

**Comment by noumanpowersoft19** [comment] 2018-02-22 14:51
@amitghodke90 @ctron  please help me ,
my application is crashing on KuraMqtttProfile.newProfile(FuseClientBuilder) here

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.example.noumanjamil.pahoservice, PID: 18771
                                                                                     java.lang.NoClassDefFoundError: com.example.noumanjamil.pahoservice.MainActivity$$Lambda$0
                                                                                         at com.example.noumanjamil.pahoservice.MainActivity.Connect(MainActivity.java:40)
                                                                                         at com.example.noumanjamil.pahoservice.MainActivity.onCreate(MainActivity.java:31)
                                                                                         at android.app.Activity.performCreate(Activity.java:6010)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by ctron** [comment] 2018-02-22 17:48
It looks like you are missing some classes in your classpath. And the exception stack trace seems incomplete.

**Comment by noumanpowersoft19** [comment] 2018-02-22 19:24
@ctron my same code is working fine on emulator and  on real device i think it is crashing because mobile is not on same network on which my kapua server is installed.
When i run application on emulator it works fine but not able to make connection with kapua. 
My same code is working fine for Eclipse maven project where i successfully establish connection and pass my data there.

**Comment by noumanpowersoft19** [comment] 2018-02-22 19:26
it might help you understanding my problem. Here is some information i got from Logcat. 
When i try to run my application from Emulator it run well without any crashing but giving an exception.
Here is Logcat 

02-23 00:22:54.590 3442-3442/? I/art: Not late-enabling -Xcheck:jni (already on)
02-23 00:22:54.591 3442-3442/? W/art: Unexpected CPU variant for X86 using defaults: x86
02-23 00:22:54.609 3442-3442/? W/System: ClassLoader referenced unknown path: /data/app/com.example.noumanjamil.pahoservice-2/lib/x86
02-23 00:22:54.629 3442-3442/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-23 00:22:54.661 3442-3442/com.example.noumanjamil.pahoservice W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
02-23 00:22:54.662 3442-3442/com.example.noumanjamil.pahoservice W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
02-23 00:22:54.662 3442-3442/com.example.noumanjamil.pahoservice W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err: java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.sendBirthCertificate(KuraBirthCertificateModule.java:160)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.applicationAdded(KuraBirthCertificateModule.java:125)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.lambda$notifyAddApplication$1$AbstractClient(AbstractClient.java:93)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient$$Lambda$1.accept(Unknown Source)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.fireModuleEvent(AbstractClient.java:85)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.notifyAddApplication(AbstractClient.java:93)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.internalBuildApplication(AbstractClient.java:148)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient$2.build(AbstractClient.java:134)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at com.example.noumanjamil.pahoservice.MainActivity.Connect(MainActivity.java:51)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at com.example.noumanjamil.pahoservice.MainActivity.onCreate(MainActivity.java:33)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
02-23 00:22:54.715 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.os.Looper.loop(Looper.java:154)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-23 00:22:54.716 3442-3442/com.example.noumanjamil.pahoservice E/Exception: java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
02-23 00:22:55.036 3442-3449/com.example.noumanjamil.pahoservice I/art: Ignoring second debugger -- accepting and dropping
02-23 00:22:56.411 3442-3464/com.example.noumanjamil.pahoservice I/OpenGLRenderer: Initialized EGL, version 1.4
02-23 00:22:56.411 3442-3464/com.example.noumanjamil.pahoservice D/OpenGLRenderer: Swap behavior 1
02-23 00:22:56.412 3442-3464/com.example.noumanjamil.pahoservice W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
02-23 00:22:56.412 3442-3464/com.example.noumanjamil.pahoservice D/OpenGLRenderer: Swap behavior 0

**Comment by noumanpowersoft19** [comment] 2018-02-22 19:32
@ctron Please help me on this issue, i am trying from days and i wrote an email to you some days ago when i was facing issue in finding gradle dependencies . I have tried very hard to convert my eclipse maven project into android application but now stuck in this little problem

**Comment by ctron** [comment] 2018-02-22 19:32
It looks like you are not running with Java 8 support.

**Comment by noumanpowersoft19** [comment] 2018-02-22 19:35
@ctron  this is my buil.gradle (Module app)

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.noumanjamil.pahoservice"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        /*jackOptions{
            enabled true
        }*/
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    compile 'de.dentrassi.kapua:kapua-gateway-client-provider-mqtt-fuse:0.2.1'
    compile 'de.dentrassi.kapua:kapua-gateway-client-profile-kura:0.2.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

**Comment by noumanpowersoft19** [comment] 2018-02-22 19:37
@ctron  what i need to do more i have already set compileOptions with JavaVersion 8

**Comment by ctron** [comment] 2018-02-22 19:51
I don't know that.

**Comment by noumanpowersoft19** [comment] 2018-02-22 19:53
@ctron any link or android sample blog from where i can resolve it even if i have to do from scratch i will do. Its very critical for me.

**Comment by ctron** [comment] 2018-02-22 19:57
I can only recommend to check the Android SDK documentation.

**Comment by amitghodke90** [comment] 2018-02-23 09:18
@noumanpowersoft19 https://github.com/amitghodke/KuraAndroidClient here is my working example of kapua connection with kura client.

**Comment by noumanpowersoft19** [comment] 2018-02-23 10:03
@amitghodke90  thanks for your reply.

Application is crashing on this line final Application application = builder.build();

here is Logcat information

**Comment by amitghodke90** [comment] 2018-02-23 10:05
om which android version you running??
the app will run on android 8.0 on words.

**Comment by noumanpowersoft19** [comment] 2018-02-23 10:09
@amit you mean to say application will not run on android nougat and less ?

**Comment by amitghodke90** [comment] 2018-02-23 10:11
No. because JAVA 8 is not supported  on android api less than 26.

**Comment by noumanpowersoft19** [comment] 2018-02-23 10:12
@amitghodke90 i run this application on Virtual Device with api 25 that's why it was crashing ?

**Comment by amitghodke90** [comment] 2018-02-23 10:12
yes.

**Comment by noumanpowersoft19** [comment] 2018-02-23 10:15
@amitghodke90 any way to run it on api less than 26 ?

**Comment by amitghodke90** [comment] 2018-02-23 10:17
No , i don't think so, and i couldn't found any solution for api less than 26.
If you found any update let me know.

**Comment by noumanpowersoft19** [comment] 2018-02-23 10:35
@amitghodke90 application is not crashing now on api 26 but it gets stuck while loading and this warning comes

amittestapp.admin.example.com.tcpconnectdemo W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
02-23 15:33:19.694 10966-10966/amittestapp.admin.example.com.tcpconnectdemo W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
02-23 15:33:19.694 10966-10966/amittestapp.admin.example.com.tcpconnectdemo W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by amitghodke90** [comment] 2018-02-23 11:25
just confirm you changed broker url and username ,password with your credentials.

**Comment by noumanpowersoft19** [comment] 2018-02-23 11:28
@amitghodke90 yes i have changed them
  .accountName("kapua-sys")
                    .clientId(android_client)
                    .brokerUrl("tcp://qazam:1883/")
                    .credentials(userAndPassword("kapua-broker", "kapua-password"))
                    .build();

**Comment by noumanpowersoft19** [comment] 2018-02-23 12:08
@amitghodke90  any clue how to fix this ?

i have add jar file of slf4j in my build.gradle but application is still stuck and print this message on logcat
INFO org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule - Application added: Demo

**Comment by noumanpowersoft19** [comment] 2018-02-23 16:15
@amitghodke90 @ctron  application stuck on this line " waitForConnection(application.transport()); " if i comment this line then i got stuck here "  application.data(Topic.of("Android Data", "Data")).subscribe(
                    new MessageHandler() {

                        public void handleMessage(Payload message) {
                            Log.e("Message",message.toString());
                            System.out.format("Received: %s%n", message);
                        }
                    });
//	                        message -> {
//	                    System.out.format("Received: %s%n", message);
            //});  "

I think problem is in android device connection with Kapua .. application is not establishing any connection with Kapua thats why i am not able to send any data there. 
if i remove this code for subscribe  application works fine without any hang in UI. This message is printed  on Logcat " INFO org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule - Application added: Demo " while there is no data against this topic.

**Comment by noumanpowersoft19** [comment] 2018-03-09 12:25
@amitghodke90  your repository did'nt help out me . is there any way u help out me to establish connection and push telemetry data . My application gets stuck when invoke activity of kapua connection. running my application on api 26 emulator  
I would be very thankful to you
