### ISSUE TITLE
Kapua Reports Unsaved Changes Although There Are Not Any

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#930] opened 2017-11-07 09:46 UTC
When a device is connected to Kapua and user navigates through Configuration Services, Kapua reports unsaved changes, although user did not change or modify anything. This happens only when clicking on _**MQTTDataTransport**_ or _**RestService**_ . 
It is not a critical issue, but user could easily get confused because of this. 

Testflow: 
1. Login as kapua-sys
2. Connect a device to Kapua
3. Go to Devices -> Configuration -> Services -> MQTTDataTransport/RestServices
**Although user does not change anything, Kapua returns an _unsaved changes error_ when navigating away**.

<img width="1440" alt="screen shot 2017-11-07 at 10 38 18" src="https://user-images.githubusercontent.com/15121999/32487034-bdaf3f6c-c3a8-11e7-8f82-05391f9cfed4.png">

Browsers used:

- Google Chrome (Version 62.0.3202.75 (Official Build) (64-bit))
- Safari (Version 11.0.1 (12604.3.5.1.1))
- Mozilla Firefox (56.0.2 (64-bit))
- Opera (Version 48.0.2685.52)

**Comment by lorthirk** [comment] 2018-02-01 11:04
This should be covered by #1098 and fixed in branch `fix-devices_view_usability_improvements`. Can you confirm?

**Comment by LeoNerdoG** [comment] 2018-02-01 11:25
@lorthirk yes, that is correct. This issue is sucessfully fixed in branch `fix-devices_view_usability_improvements`.

**Comment by lorthirk** [comment] 2018-02-01 11:33
Duplicate of #1098 (not strictly duplicate, but fully included anyway)

**Comment by lorthirk** [comment] 2018-02-01 11:34
Although not strictly a duplicate, since #1098 is also about other stuff, we can keep track of this issue there.

**Closed by lorthirk** 2018-02-01 11:33 UTC
Labels: console-gwt
