### ISSUE TITLE
Cannot Add Permissions to Roles

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#893] opened 2017-10-19 13:57 UTC
When creating new roles, we cannot add permissions to it. We can click on Permissions tab and Add button, but when Add New Permission windows pops-up, Domain and Action fields are empty (we can "choose" one of the empty "choices", but Kapua rejects them, because they are - empty). 

Testflow: 
1) Login as kapua-sys
2) Go to Roles and select one of the existing ones or create new one
3) Click on one of the roles, go to its Permissions, and Add new permissions. 
**After we click Add button, we get pop-up windows as seen on screenshots bellow. **

<img width="1440" alt="screen shot 2017-10-19 at 15 43 03" src="https://user-images.githubusercontent.com/15121999/31774336-ae695474-b4e5-11e7-98d0-ddde0b22cef7.png">

<img width="1438" alt="screen shot 2017-10-19 at 15 43 09" src="https://user-images.githubusercontent.com/15121999/31774348-b94c62be-b4e5-11e7-8fac-c429d06c189c.png">

Browser used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by Coduz** [comment] 2017-11-07 15:34
Assigned to lorthirk since this issue is beign fixed by Bojan

**Comment by lorthirk** [comment] 2017-11-10 17:01
Confirmed fixed

**Closed by lorthirk** 2017-11-10 17:01 UTC
Labels: bug, console-gwt
