### ISSUE TITLE
No Upper Limit For Assets Field in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1158] opened 2017-12-08 13:26 UTC
User can enter any number of characters in job assets field - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Select _**Device Asset Management Write**_ in Step definition
3. Enter very long string of characters into _**assets**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

Screenshot No. 1 (Adding long string of characters): 
<img width="1437" alt="screen shot 2017-12-08 at 14 23 50" src="https://user-images.githubusercontent.com/15121999/33767732-4df3416c-dc23-11e7-950a-f7a041a170cb.png">

Screenshot No. 2 (Kapua freezes for a while, when trying to edit the job step):
<img width="1438" alt="screen shot 2017-12-08 at 14 23 17" src="https://user-images.githubusercontent.com/15121999/33767733-50b91f8e-dc23-11e7-908c-91b359335772.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by ct-ajovanovic** [comment] 2018-03-06 14:48
Hi @lorthirk 
I've been looking at few similar issues (#1160, #1161, #1162, #1164). 
The problem is the same - upper limit for TextArea field, and all would be solved with one change.
Using special KapuaTextArea class (similar to KapuaTextField) , would be a good solution but I couldn't find it in the project. Is there such a class? Or should it be created? 
Can I do it? I could use the already there KapuaTextField class as a guide.
Thanks

**Comment by lorthirk** [comment] 2018-03-06 16:34
Hi @ct-ajovanovic,

Your approach is surely the correct one. There's no KapuaTextArea at the moment, so you can surely create one replicating `KapuaTextField`.

However, this will not be enough to complete these issues since we need a customizable limit, not a fixed one, and such customization would require a change in a few models. I can start working on this tomorrow, so I will leave you the frontend part of this and similar issues.

**Comment by lorthirk** [comment] 2018-03-06 16:49
Hi @ct-ajovanovic,

While you are right that we don't have a `KapuaTextArea` and we could implement one that resembles `KapuaTextField`, I'm afraid we shouldn't apply it in this case. At least some of the JobStepProperties (especially the ones with an associated `TextArea` inherently have no limit at all, and should stay this way because we cannot limit the input from the user even if quite big, since it can be an XML serialization even from a complex object.

**Comment by muros-ct** [comment] 2018-03-22 13:58
This closes this issue.
In case of possible attack with too long requests it can be solved with filter on server side.
If browser chashes because to big input in TextArea, this is not a problem for backend.

**Closed by muros-ct** 2018-03-22 13:58 UTC
Labels: console-gwt, enhancement
