### ISSUE TITLE
Broker stops inserting data into Elasticsearch

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#644] opened 2017-06-06 13:17 UTC
While trying to do some load testing with Kapua I now ran multiple times into the same issue. When a client pushes data "too quickly" into the broker the following messages appears in the log:

```
13:13:10.241 [Camel (camelContext) thread #1 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] INFO  o.e.k.s.d.c.t.TransportDatastoreClient - Upsert failed [.1, metric, [.1/WeeR2530TLumJJTTbdyctg][[.1][0]] VersionConflictEngineException[[metric][fKKD32WQvDLr1K580S/AeGaKzB0LsBreoAlEcAaT7Lo=]: version conflict, document already exists (current version [1])]]
13:13:15.524 [Camel (camelContext) thread #1 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] INFO  o.e.k.s.d.c.t.TransportDatastoreClient - Upsert failed [.1, metric, [.1/WeeR2530TLumJJTTbdyctg][[.1][0]] VersionConflictEngineException[[metric][KPpbraa1hy1gZVsHVj1tAgVd7R2FwnmsVk+h1MhxDxg=]: version conflict, current version [2] is different than the one provided [1]]]
13:13:15.527 [Camel (camelContext) thread #1 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] INFO  o.e.k.s.d.c.t.TransportDatastoreClient - Upsert failed [.1, metric, [.1/WeeR2530TLumJJTTbdyctg][[.1][0]] VersionConflictEngineException[[metric][7XUS7JZqOg7aQNx+/wla6J1tLs90qPc7mUuZ/ALoRXc=]: version conflict, current version [2] is different than the one provided [1]]]
13:13:16.399 [Camel (camelContext) thread #2 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] INFO o.e.k.s.d.c.t.TransportDatastoreClient - Upsert failed [.1, metric, [.1/WeeR2530TLumJJTTbdyctg][[.1][0]] VersionConflictEngineException[[metric][gfK9oKKDXlh95bsrLfChsYdZIz5YOZpmaQcrBeK9hrI=]: version conflict, document already exists (current version [1])]]
```

And then the connection stays open, but doesn't insert anymore data into ES. Destroying and re-opening the connections seems to work.

**Comment by riccardomodanese** [comment] 2017-06-22 16:43
Hi Jens, are you experiencing this issue on a Docker environment, right?
Could you provide me some additional info about your docker machine settings and parametrization you are using to launch the containers?

**Comment by ctron** [comment] 2017-06-23 07:09
I just fire up the default OpenShift installation.

**Comment by riccardomodanese** [comment] 2017-06-25 09:47
Hi Jens, we weren't able to reproduce it (using develop branch as was on Thursday 22th).
We tried publishing at different rate (from 1 msg/s to 5 msg/s) with Paho client using, as target platform, both Docker and also OpenShift but we didn't see any issue.
Our test runs varied between half an hour to more then 10 hours.
Did the issue come up soon after the output log line you posted?

**Comment by ctron** [comment] 2017-06-26 07:15
Yes, I think it does.

**Comment by ctron** [comment] 2017-06-26 13:54
I played around a little bit with it, I can force it into the error message by either setting the broker under high load or by creating a new client-id and firing this up with a high frequency of messages from the start.

However it looks like the messages still get stored. So I cannot reproduce this issue. Maybe something already got fixed in the last weeks.

I guess this is some sort of race condition where two threads update information at the same time. But I didn't dig through all call graphs to back up this assumption.

**Comment by riccardomodanese** [comment] 2017-06-26 14:25
The log line you noticed is not an issue at all. Based on our data schema, version conflicts may occur when the same entity is published at high frequency until ES does its indexing refresh.
Or if similar messages, not already indexed, are published to different broker instances more or less at the same time. So we have a refresh_time window in which similar log lines can be noticed for every message that contains new informations (channel, client or metrics) not alredy indexed.
Since is not an issue and there is no way to avoid this condition whithout impacting in the performance, I wasn't considering that as an issue, but the missed storing for the subsequent messages.
In our test we did messages count and that count confirmed that no message lost were occurred.
So may be that we had that issue in the past and now it is fixed as result of other datastore fixes. 
In any case, if you agree, we can keep this issue open for a while and track any other additional information related to that issue here.

**Comment by ctron** [comment] 2017-06-26 14:56
Well, I had the issue of messages being not inserted anymore when publishing with high frequencies and it seems I am not the only person. I did relate it to this message, but maybe that assumptions doesn't hold true. So maybe the issue is located elsewhere.

**Comment by riccardomodanese** [comment] 2017-06-26 15:07
ok, so after a while a missed storing messages were noticed.
Unfortunately, being not able to reproduce it make the investigation very hard.
Did you see any other strange log line in the broker log or in the ES server side?
Lets keep open the issue and, if you have any additional information about it please add it.

**Comment by kartben** [comment] 2017-06-27 09:43
> We tried publishing at different rate (from 1 msg/s to 5 msg/s) with Paho client using, as target platform, both Docker and also OpenShift but we didn't see any issue.

FWIW this doesn't look like a very aggressive load testing scenario?

**Comment by riccardomodanese** [comment] 2017-06-27 09:53
I agree but it depends on the target machine. Deploying the whole environment in a Docker container with 2GB assigned a publish rate of 5msg/s may be not aggressive but also not too light.
In any case our tests were based on what reported @ctron when he described the issue in the Kapua scum.
His test was based on a publish rate of 2msg/s if I remember correctly.

**Comment by ctron** [comment] 2017-06-27 12:39
4 msg/s ... 250ms delay ... Which should be handles easily. However my setup did have more than 2 GB or RAM. It was more like 16GB of RAM which IMHO should be more than enough for handling thousands of messages per second.

**Comment by riccardomodanese** [comment] 2017-06-27 13:42
@ctron my intention wasn't to open a discussion about which could be an agressive rate or not without having defined a stress target platform and a stress test load. And honestly, I'm assuming this issue is not related to the load in the system.
Since from my stress test experience I can say that the message rate achievable is widely affected by the message size (metrics numbers/type, raw message payload size), QoS, connections count and registered destinations (topics), before evaluating which could be a rasonable stress load for the system IMHO we should evaluate these aspects.
I was just trying to reproduce the issue so going close to your target environment and your publishing rate.
Just to recap you used an OpenShift deployment with 16GB for the whole Docker containers (H2, ES, Kapua-broker, Kapua-api, Kapua-console) and you published a message every 250ms with few metrics on the same topic. Right?

**Comment by ctron** [comment] 2017-06-27 14:21
Yes, that is correct. Actually I was only publishing from one application/topic, with a single metric.

Well I think it might be that the issue is related to system load. It this is indeed some race condition, when a higher system load and a higher number of messages might trigger this problem more frequently.

**Comment by riccardomodanese** [comment] 2017-06-27 14:43
mmm it's coming another idea in my mind... I'm wondering if could be related to the bind/unbind of the KapuaSecurityContext in the ThreadLocal made by Camel workers.
But in that case you should see some log error line about unauthenticated or unauthorized session.
I could perform other tests raising the publish rate and may be changing the Camel thread pool size.

**Comment by riccardomodanese** [comment] 2017-09-11 09:37
Hi @ctron, I did tests changing both the publish frequency rate and the camel subscribers count and I wasn't able to reproduce the issue.
So I'm closing the issue.
In any case we can reopen the ticket (or open a new one) If we will have any news on that.

Regards

**Closed by riccardomodanese** 2017-09-11 09:37 UTC
Labels: bug
