### ISSUE TITLE
Device edit not working

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#993] opened 2017-11-16 22:12 UTC
Testflow:

* Connect to kapua-sys as kapua-sys
* Open the device view
* Manually add a new device
* Submit
* Select the device
* Press the edit button

The edit form pops up for a moment then disappears, an error reports: "Error loading device: last unit does not have enough valid bits"

**Comment by LeoNerdoG** [comment] 2017-11-17 07:02
Hi @stefanomorson ,
this bug is already added. It is issue #985 .

**Comment by lorthirk** [comment] 2017-11-17 08:00
Duplicate of #985

**Closed by lorthirk** 2017-11-17 08:00 UTC
Labels: bug, console-gwt
